package Lab.Model;

import lombok.*;

/**
 * Lombok is a took that can automatically generate boilerplate code such as ToString,
 * Equals, HashCode, Constructors, and all the needed getters/setters at runtime. Lombok is not part of Spring,
 * but will be quite useful for making our model classes from here on out. This model class will have fully functional
 * code in all of these respects - getters and setters that you may use, constructors, equals, etc, despite the class
 * appearing empty. You can see these in use in the Application class's main method.
 *
 * Note: Lombok relies on a feature called 'annotation preprocessing'. If methods that ought to be generated by
 * Lombok are unavailable, you might need to enable annotation preprocessing in your IDE.
 *
 * There is no need to change anything in this class.
 */
@Getter
@Setter
@ToString
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode
public class Town {
    public long id;
    public String name;
    public String state;
}
